### ISSUE TITLE
Please release last version from main

### ISSUE THREAD

**Issue by atsonkov** [puppets-epic-show-theatre/action-pdk-test-unit#1]
Hi Team,

This is just what I was looking for!
I noticed, that specifying puppet version works on the validate action, and this one seems to contain everything on main branch, but it is not released. Tag v1 (and  v1.0.0) do not contain the latest changes.

May I ask that you release a version with the latest changes in main (so I can pin my action to that version)?

**Comment by TuningYourCode** [comment]
Hi,
we tagged a new version so you should be able to use it.

We stick to semantic versioning so you should be able to pin "v1" :)

Best regards,
Stephan

**Comment by atsonkov** [comment]
Now v1 works with the selected puppet version as expected.
And that was blazing fast!
Thanks a lot!
